[package]
name = "llama-ash"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "llama_ash"
path = "src/lib.rs"

[[bin]]
name = "llama_ash"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
env_logger = "0.11"
log = "0.4"
tensor-ash = { path = "../.." }
